pygments: true

title: Mister Cantini

url: http://localhost:4000
url: http://mistercantini.github.io

permalink: /:year/:month/:day/:title/

author:
    name: Jason Brown
    email: jasonandrewbrown@me.com
    github: mistercantini
    twitter: jasonb5232

comments:
    provider: disqus
    disqus:
        short_name: mistercantini
